STAR-1743: Fix compilation on JDK11
Remove unnecessary import of sun.nio.ch.DirectBuffer.
Minor cleanup: Remove some other unused imports.

Fixes:

    _build_java:
         [echo] Compiling for Java 11...
        [javac] Compiling 2289 source files to /home/pkolaczk/Projekty/DataStax/cassandra/build/classes/main
        [javac] Note: Processing compiler hints annotations
        [javac] /home/pkolaczk/Projekty/DataStax/cassandra/src/java/org/apache/cassandra/io/util/FileUtils.java:72: error: package sun.nio.ch is not visible
        [javac] import sun.nio.ch.DirectBuffer;
        [javac]               ^
        [javac]   (package sun.nio.ch is declared in module java.base, which does not export it to the unnamed module)
        [javac] Note: Processing compiler hints annotations
        [javac] Note: Writing compiler command file at META-INF/hotspot_compiler
        [javac] Note: Done processing compiler hints annotations
        [javac] 1 error