Fix compilation of MessagingService (#595)
Fixes:
  [javac] cassandra/src/java/org/apache/cassandra/net/MessagingService.java:219: error: cannot find symbol
    [javac]     static Map<Integer, Integer> versionOrdinalMap = Arrays.stream(Version.values()).collect(Collectors.toMap(v -> v.value, v -> v.ordinal()));
(cherry picked from commit 4904d4f2fd199f18e63c39590481fe4123c9c3d9)